name: Nightly trigger
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 8 * * *'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Build All Root Manager
        run: |
          gh workflow run build.yml \
            -f enable_all_roots=true 
        env:
          GH_TOKEN: ${{ secrets.NIGHTLY_PAT }}
      - name: Build ReSukiSU Manager with SUSFS
        run: |
          gh workflow run build.yml \
            -f enable_resukisu=true
            -f enable_susfs=true
        env:
          GH_TOKEN: ${{ secrets.NIGHTLY_PAT }}
